include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # treat missing required parameters as an error (not a hint)
    missing_required_param: error
    # treat missing returns as errors
    missing_return: error
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
    deprecated_member_use_from_same_package: ignore
    # TODO(ianh): https://github.com/flutter/flutter/issues/35172
    #
    # Waiting for this issue to be resolved to enforce this lint
    null_check_on_nullable_type_parameter: ignore
  exclude:
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    # Style rules
    always_use_package_imports: true  # Enforce package imports
    avoid_web_libraries_in_flutter: true
    directives_ordering: true
    prefer_relative_imports: false  # Disable relative imports
    sort_pub_dependencies: true

    # Error rules
    avoid_empty_else: true
    avoid_print: true  # Avoid using print in production code
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    
    # Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_single_cascade_in_expression_statements: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    overridden_fields: true
    package_api_docs: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_rethrow_when_possible: true